POST https://library-app-txh.herokuapp.com/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1eTEiLCJpZCI6IjYyYmFmMDY5ZjNiYTgzYmExODA2NGY3MSIsImlhdCI6MTY1NjQxODQyMX0.oOm24UGjn2-Z-qBYR-p06xCc535Z9H4Cg6HSMIkXmc4

{
  "query":  "allAuthors {
    bookCount
    name
    born
  }"
}